### ISSUE TITLE
Data Synchronization failing

### ISSUE THREAD

**Issue by openctitest** [LuatixHQ/opencti#3794]
## Description

I have 3 opencti clusters, one is the primary and two are secondary. On the primary I have a live stream set up as public. On the two secondary clusters, I have synchronizers set up to pull in the data from the primary. On synchronization, I'm getting an error on the primary platform "[STIX] Missing definition for Threat-Actor<-users->Malware". The primary continues to throw this error on each synchronization attempt by the secondary clusters.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
Centos7

2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
5.9.2

3. OpenCTI client: { e.g. frontend or python }
frontend

4. Other environment details:
Docker containers

## Reproducible Steps

Steps to create the smallest reproducible scenario:
I cannot copy my data from our closed network and it is a fairly large dataset. I tried upping the logs to debug but that didn't provide any obvious info on what in the data it doesn't like specifically

## Expected Output
Expect synchronization to skip this "bad data" or provide clear information on which records are causing this failure

## Actual Output
Continual error and failure to synchronize

**Comment by SamuelHassine** [comment]
Hello @openctitest,

Taking a look right now. We have a pretty good idea about what is causing those errors, still investigating.

**Comment by SamuelHassine** [comment]
This should be fixed in 5.9.4. Please re-open an issue if it is not the case.

**Comment by SamuelHassine** [comment]
5.9.4 to be released now.

**Comment by openctitest** [comment]
Thanks, I'll verify it today

**Comment by openctitest** [comment]
@SamuelHassine I the cluster instances to 5.9.4 and I'm still seeing the same error. It throws it right away now when I attempt to sync, previously it had been able to sync over 3000 or so entities before it failed.

**Comment by SamuelHassine** [comment]
Hello,

Still the same logs?

Do you have access to Kibana? Are you able to jump on a call with our team for a troubleshoot session?

**Comment by openctitest** [comment]
Still the same logs, yes. I do have access to Kibana, is there anything in particular I should look for?

**Comment by SamuelHassine** [comment]
Hello,

Yes, on all `opencti_*` indices, in "Discover", do the following query:

```fromType.keyword: "threat-actor"```

And see how many results you have.

**Comment by SamuelHassine** [comment]
You should have none.

**Comment by openctitest** [comment]
Correct, I have no results

**Comment by SamuelHassine** [comment]
Ok thanks, it will be fixed in 5.9.5.

**Comment by openctitest** [comment]
Great thanks! I'll verify when it gets released

**Comment by SamuelHassine** [comment]
We will release in 1 hours approx.

**Comment by openctitest** [comment]
Thanks!

**Comment by openctitest** [comment]
Synchronizing now. Going to let it finish to make sure but I'm no longer seeing the error. Thanks for the quick fix!
